name: Lint
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Use Node.js with cache
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Update npm
        run: npm -g install npm@latest

      - name: Install Packages
        run: npm install

      - name: Run Lint
        run: npm run lint
